"""Subclass of RowConstraint, which is generated by wxFormBuilder."""

import wx
import GUI.py

# Implementing RowConstraint
class AdvisorGUIRowConstraint( GUI.py.RowConstraint ):
	def __init__( self, parent ):
		GUI.py.RowConstraint.__init__( self, parent )
	
