"""Subclass of SpecPage, which is generated by wxFormBuilder."""

import wx
import GUI.py

# Implementing SpecPage
class AdvisorGUISpecPage( GUI.py.SpecPage ):
	def __init__( self, parent ):
		GUI.py.SpecPage.__init__( self, parent )
	
	# Handlers for SpecPage events.
	def OnInType1( self, event ):
		# TODO: Implement OnInType1
		pass
	
	def OnInType2( self, event ):
		# TODO: Implement OnInType2
		pass
	
	def OnInAddConstraint( self, event ):
		# TODO: Implement OnInAddConstraint
		pass
	
	
